In [52]:
import pandas as pd

df=pd.read_csv("consumer_shopping_behavior_survey.csv")
print(df)

     Response_ID            Timestamp  Age             Gender  \
0              1  01/08/2026 12:30:25   20               Male
1              2  21/06/2026 13:52:02   24               Male
2              3  15/08/2026 04:24:18   22             Female
3              4  23/06/2026 21:24:21   20               Male
4              5  20/08/2026 16:24:47   41               Male
..           ...                  ...  ...                ...
495          496  18/07/2026 23:18:07   42             Female
496          497  28/06/2026 15:20:50   22  Prefer not to say
497          498  23/06/2026 05:27:31   26               Male
498          499  17/07/2026 08:05:20   37             Female
499          500  14/07/2026 11:16:14  NaN             Female

      Occupation_Status  Country_Region Monthly_Income_Range Shop_Most_Where  \
0                   NaN     Philippines         Under $1,000       Equal mix
1    Employed part-time          Brazil         Under $1,000   In-store only
2               Student           India         Under $1,000       Equal mix
3               Student             NaN         Under $1,000   In-store only
4    Employed full-time   United States         $1,000-3,000       Equal mix
..                  ...             ...                  ...             ...
495  Employed full-time           India         $1,000-3,000     Online only
496                 NaN        Colombia         Under $1,000     Online only
497             Student          Brazil                  NaN       Equal mix
498  Employed full-time  United Kingdom              $6,000+   In-store only
499             Student         Turkiye         $3,000-6,000       Equal mix

    Online_Shopping_Frequency                Preferred_Platform  ...  \
0                       Often                   Physical stores  ...
1                       Often                  Local e-commerce  ...
2                      Always                  Local e-commerce  ...
3                Occasionally                    Brand websites  ...
4                Occasionally                               NaN  ...
..                        ...                               ...  ...
495                     Often  Global marketplace (Amazon etc.)  ...
496              Occasionally  Global marketplace (Amazon etc.)  ...
497                     Often                    Brand websites  ...
498              Occasionally  Global marketplace (Amazon etc.)  ...
499                       NaN                    Brand websites  ...

    Return_Frequency Avg_Monthly_Spend_NonEssentials  \
0              Never                       Under $50
1              Often                       Under $50
2          Sometimes                        $150-300
3              Never                       Under $50
4          Sometimes                         $50-150
..               ...                             ...
495            Never                       Under $50
496            Often                       Under $50
497            Never                        $150-300
498            Never                         $50-150
499            Never                           $500+

     Preferred_Payment_Method  Uses_BNPL_Installments  \
0              Digital wallet       Yes, occasionally
1              Digital wallet               No, never
2                 Credit Card               No, never
3                  Debit Card               No, never
4                  Debit Card               No, never
..                        ...                     ...
495            Digital wallet          Yes, regularly
496            Digital wallet               No, never
497            Digital wallet               No, never
498            Digital wallet               No, never
499            Digital wallet       Yes, occasionally

     Online_Shopping_Satisfaction_Score  Trust_In_Online_Reviews_Score  \
0                                   6.0                            7.0
1                                   5.0                            8.0
2                                   7.0                            6.0
3                                   8.0                            7.0
4                                   6.0                            8.0
..                                  ...                            ...
495                                 4.0                            5.0
496                                 9.0                            5.0
497                                 8.0                            5.0
498                                 8.0                           10.0
499                                 7.0                           10.0

    Regret_After_Purchase_Frequency  Reason_Prefer_Online  \
0                               2.0          More variety
1                               3.0                   NaN
2                               2.0         Better prices
3                               3.0         Better prices
4                               2.0           Convenience
..                              ...                   ...
495                             2.0          More variety
496                             2.0          More variety
497                             1.0         Better prices
498                             2.0          More variety
499                             1.0           Convenience

         Reason_Prefer_InStore  Best_Shopping_Mode
0             No delivery wait              Online
1    Try product before buying             Offline
2                        Trust              Online
3    Try product before buying        Equal / both
4                        Trust        Equal / both
..                         ...                 ...
495  Try product before buying              Online
496  Try product before buying        Equal / both
497                      Trust             Offline
498                      Trust             Offline
499           No delivery wait             Offline

[500 rows x 30 columns]

In [53]:
df.columns

Index(['Response_ID', 'Timestamp', 'Age', 'Gender', 'Occupation_Status',
       'Country_Region', 'Monthly_Income_Range', 'Shop_Most_Where',
       'Online_Shopping_Frequency', 'Preferred_Platform', 'Primary_Device',
       'Top_Spending_Category', 'Review_Influence_Score',
       'Social_Ads_Influence_Score', 'Price_Comparison_Frequency',
       'Discount_Importance_Score', 'Follows_Brands_On_Social',
       'Likely_To_Buy_After_Ad_Score', 'Makes_Shopping_List',
       'Impulse_Purchase_Frequency', 'Return_Frequency',
       'Avg_Monthly_Spend_NonEssentials', 'Preferred_Payment_Method',
       'Uses_BNPL_Installments', 'Online_Shopping_Satisfaction_Score',
       'Trust_In_Online_Reviews_Score', 'Regret_After_Purchase_Frequency',
       'Reason_Prefer_Online', 'Reason_Prefer_InStore', 'Best_Shopping_Mode'],
      dtype='object')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Response_ID                         500 non-null    int64
 1   Timestamp                           500 non-null    object
 2   Age                                 478 non-null    object
 3   Gender                              484 non-null    object
 4   Occupation_Status                   479 non-null    object
 5   Country_Region                      480 non-null    object
 6   Monthly_Income_Range                479 non-null    object
 7   Shop_Most_Where                     484 non-null    object
 8   Online_Shopping_Frequency           481 non-null    object
 9   Preferred_Platform                  486 non-null    object
 10  Primary_Device                      492 non-null    object
 11  Top_Spending_Category               476 non-null    object
 12  Review_Influence_Score              485 non-null    float64
 13  Social_Ads_Influence_Score          479 non-null    float64
 14  Price_Comparison_Frequency          474 non-null    float64
 15  Discount_Importance_Score           477 non-null    float64
 16  Follows_Brands_On_Social            489 non-null    object
 17  Likely_To_Buy_After_Ad_Score        475 non-null    float64
 18  Makes_Shopping_List                 476 non-null    object
 19  Impulse_Purchase_Frequency          484 non-null    float64
 20  Return_Frequency                    483 non-null    object
 21  Avg_Monthly_Spend_NonEssentials     480 non-null    object
 22  Preferred_Payment_Method            485 non-null    object
 23  Uses_BNPL_Installments              488 non-null    object
 24  Online_Shopping_Satisfaction_Score  457 non-null    float64
 25  Trust_In_Online_Reviews_Score       450 non-null    float64
 26  Regret_After_Purchase_Frequency     448 non-null    float64
 27  Reason_Prefer_Online                446 non-null    object
 28  Reason_Prefer_InStore               455 non-null    object
 29  Best_Shopping_Mode                  449 non-null    object
dtypes: float64(9), int64(1), object(20)
memory usage: 117.3+ KB

In [55]:
print(df.isnull().sum())
print(df.duplicated().sum())

Response_ID                            0
Timestamp                              0
Age                                   22
Gender                                16
Occupation_Status                     21
Country_Region                        20
Monthly_Income_Range                  21
Shop_Most_Where                       16
Online_Shopping_Frequency             19
Preferred_Platform                    14
Primary_Device                         8
Top_Spending_Category                 24
Review_Influence_Score                15
Social_Ads_Influence_Score            21
Price_Comparison_Frequency            26
Discount_Importance_Score             23
Follows_Brands_On_Social              11
Likely_To_Buy_After_Ad_Score          25
Makes_Shopping_List                   24
Impulse_Purchase_Frequency            16
Return_Frequency                      17
Avg_Monthly_Spend_NonEssentials       20
Preferred_Payment_Method              15
Uses_BNPL_Installments                12
Online_Shopping_Satisfaction_Score    43
Trust_In_Online_Reviews_Score         50
Regret_After_Purchase_Frequency       52
Reason_Prefer_Online                  54
Reason_Prefer_InStore                 45
Best_Shopping_Mode                    51
dtype: int64
0

In [56]:
df["Age"]

0       20
1       24
2       22
3       20
4       41
      ...
495     42
496     22
497     26
498     37
499    NaN
Name: Age, Length: 500, dtype: object

In [57]:
df["Age"].value_counts()

Age
21         67
20         46
18         45
22         35
19         28
24         20
23         19
16         18
31         15
17         15
32         14
30         13
29         13
25         13
26         12
34         10
28          9
36          9
37          9
27          9
33          8
35          7
39          5
38          5
42          5
41          3
48          3
43          3
45          3
49          2
47          2
44          2
50          1
rahul       1
40          1
xyz         1
46          1
test        1
N/A123      1
asdf        1
...         1
Gunay B     1
Priya K     1
Name: count, dtype: int64

In [58]:
df["Age"]=pd.to_numeric(df["Age"], errors="coerce")

In [59]:
df["Age"].value_counts()

Age
21.0    67
20.0    46
18.0    45
22.0    35
19.0    28
24.0    20
23.0    19
16.0    18
17.0    15
31.0    15
32.0    14
29.0    13
25.0    13
30.0    13
26.0    12
34.0    10
37.0     9
27.0     9
36.0     9
28.0     9
33.0     8
35.0     7
39.0     5
38.0     5
42.0     5
41.0     3
48.0     3
43.0     3
45.0     3
44.0     2
47.0     2
49.0     2
50.0     1
40.0     1
46.0     1
Name: count, dtype: int64

In [60]:
df["Age"].isnull().sum()

np.int64(30)

In [61]:
df["Age"].describe()
# df["Age"].mode()

count    470.000000
mean      25.019149
std        7.515276
min       16.000000
25%       20.000000
50%       22.000000
75%       30.000000
max       50.000000
Name: Age, dtype: float64

In [62]:
df["Age"]=df["Age"].fillna(df["Age"].median()) #choosed mean for age because

In [63]:
df["Age"].value_counts()

Age
21.0    67
22.0    65
20.0    46
18.0    45
19.0    28
24.0    20
23.0    19
16.0    18
17.0    15
31.0    15
32.0    14
29.0    13
25.0    13
30.0    13
26.0    12
34.0    10
37.0     9
27.0     9
36.0     9
28.0     9
33.0     8
35.0     7
39.0     5
38.0     5
42.0     5
41.0     3
48.0     3
43.0     3
45.0     3
44.0     2
47.0     2
49.0     2
50.0     1
40.0     1
46.0     1
Name: count, dtype: int64

In [64]:
df.isnull().sum()

Response_ID                            0
Timestamp                              0
Age                                    0
Gender                                16
Occupation_Status                     21
Country_Region                        20
Monthly_Income_Range                  21
Shop_Most_Where                       16
Online_Shopping_Frequency             19
Preferred_Platform                    14
Primary_Device                         8
Top_Spending_Category                 24
Review_Influence_Score                15
Social_Ads_Influence_Score            21
Price_Comparison_Frequency            26
Discount_Importance_Score             23
Follows_Brands_On_Social              11
Likely_To_Buy_After_Ad_Score          25
Makes_Shopping_List                   24
Impulse_Purchase_Frequency            16
Return_Frequency                      17
Avg_Monthly_Spend_NonEssentials       20
Preferred_Payment_Method              15
Uses_BNPL_Installments                12
Online_Shopping_Satisfaction_Score    43
Trust_In_Online_Reviews_Score         50
Regret_After_Purchase_Frequency       52
Reason_Prefer_Online                  54
Reason_Prefer_InStore                 45
Best_Shopping_Mode                    51
dtype: int64

In [65]:
df["Gender"]

0                   Male
1                   Male
2                 Female
3                   Male
4                   Male
             ...
495               Female
496    Prefer not to say
497                 Male
498               Female
499               Female
Name: Gender, Length: 500, dtype: object

In [66]:
df["Gender"].value_counts()

Gender
Male                 256
Female               177
Prefer not to say     51
Name: count, dtype: int64

In [67]:
df["Gender"]=df["Gender"].fillna("Prefer not to say")

In [68]:
df["Gender"].isnull().sum()

np.int64(0)

In [69]:
df["Occupation_Status"].value_counts()

Occupation_Status
Student               238
Employed full-time    118
Employed part-time     71
Self-employed          33
Unemployed             19
Name: count, dtype: int64

In [70]:
df[["Occupation_Status" , "Monthly_Income_Range"]].value_counts()

Occupation_Status   Monthly_Income_Range
Student             Under $1,000            161
                    $1,000-3,000             46
Employed full-time  $1,000-3,000             37
                    $3,000-6,000             35
Employed part-time  Under $1,000             33
Employed full-time  Under $1,000             25
Employed part-time  $1,000-3,000             24
Employed full-time  $6,000+                  17
Unemployed          Under $1,000             15
Student             $3,000-6,000             13
Self-employed       $1,000-3,000             11
                    Under $1,000              8
Student             $6,000+                   8
Self-employed       $3,000-6,000              7
Employed part-time  $3,000-6,000              7
Self-employed       $6,000+                   5
Employed part-time  $6,000+                   4
Unemployed          $1,000-3,000              1
                    $3,000-6,000              1
                    $6,000+                   1
Name: count, dtype: int64

In [71]:
df[df["Occupation_Status"].isna()]

,Response_ID,Timestamp,Age,Gender,Occupation_Status,Country_Region,Monthly_Income_Range,Shop_Most_Where,Online_Shopping_Frequency,Preferred_Platform,...,Return_Frequency,Avg_Monthly_Spend_NonEssentials,Preferred_Payment_Method,Uses_BNPL_Installments,Online_Shopping_Satisfaction_Score,Trust_In_Online_Reviews_Score,Regret_After_Purchase_Frequency,Reason_Prefer_Online,Reason_Prefer_InStore,Best_Shopping_Mode
0,1,01/08/2026 12:30:25,20.0,Male,NaN,Philippines,"Under $1,000",Equal mix,Often,Physical stores,...,Never,Under $50,Digital wallet,"Yes, occasionally",6.0,7.0,2.0,More variety,No delivery wait,Online
88,89,18/07/2026 02:59:32,29.0,Male,NaN,Mexico,"$3,000-6,000",In-store only,Occasionally,NaN,...,Sometimes,$300-500,Digital wallet,"Yes, occasionally",9.0,6.0,2.0,More variety,Try product before buying,Equal / both
100,101,05/08/2026 05:12:58,18.0,Male,NaN,United States,"$1,000-3,000",NaN,Occasionally,Global marketplace (Amazon etc.),...,Often,$50-150,Digital wallet,"No, never",9.0,3.0,1.0,Not applicable,No delivery wait,NaN
109,110,09/08/2026 02:39:02,22.0,Female,NaN,Turkiye,"Under $1,000",Online only,NaN,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"Yes, occasionally",9.0,7.0,2.0,Not applicable,No delivery wait,Online
113,114,27/07/2026 10:34:09,18.0,Prefer not to say,NaN,Egypt,"Under $1,000",Online only,Often,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"No, never",4.0,4.0,2.0,Convenience,Try product before buying,Online
116,117,01/07/2026 10:28:05,21.0,Female,NaN,United Kingdom,"Under $1,000",Equal mix,Often,Physical stores,...,Sometimes,Under $50,Cash,"No, never",8.0,6.0,1.0,Better prices,Try product before buying,Offline
140,141,09/07/2026 15:14:32,25.0,Female,NaN,Pakistan,"$1,000-3,000",Equal mix,Always,Global marketplace (Amazon etc.),...,NaN,$500+,Digital wallet,"No, never",10.0,8.0,3.0,Convenience,Not applicable,Offline
157,158,12/08/2026 19:53:46,20.0,Female,NaN,South Africa,"$3,000-6,000",Online only,Occasionally,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"No, never",10.0,7.0,2.0,More variety,No delivery wait,Online
185,186,16/07/2026 14:53:01,31.0,Male,NaN,Turkiye,"Under $1,000",Equal mix,Rarely,Physical stores,...,Never,$150-300,Credit Card,"No, never",7.0,4.0,2.0,More variety,Try product before buying,Offline
194,195,20/08/2026 18:10:27,21.0,Male,NaN,United States,"Under $1,000",Online only,Occasionally,Local e-commerce,...,Sometimes,Under $50,Credit Card,"No, never",7.0,NaN,1.0,Convenience,No delivery wait,Online
216,217,22/06/2026 12:29:30,22.0,Male,NaN,Nigeria,"Under $1,000",Online only,Occasionally,Brand websites,...,Never,$50-150,Cash,"No, never",4.0,6.0,2.0,Convenience,Trust,Online
287,288,20/06/2026 22:09:01,20.0,Female,NaN,Philippines,"Under $1,000",NaN,Often,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"Yes, occasionally",7.0,7.0,1.0,More variety,Try product before buying,Online
298,299,10/07/2026 15:59:34,31.0,Female,NaN,United States,"$1,000-3,000",Equal mix,Occasionally,Local e-commerce,...,Sometimes,Under $50,Digital wallet,"No, never",9.0,NaN,4.0,Better prices,Not applicable,Offline
306,307,14/08/2026 23:37:52,20.0,Male,NaN,Colombia,"Under $1,000",Online only,Rarely,Physical stores,...,Never,Under $50,Credit Card,"No, never",6.0,10.0,2.0,More variety,No delivery wait,Online
307,308,30/06/2026 21:07:06,45.0,Male,NaN,Brazil,"Under $1,000",Equal mix,Always,Local e-commerce,...,Sometimes,Under $50,Debit Card,"Yes, regularly",NaN,NaN,NaN,NaN,NaN,NaN
355,356,07/07/2026 20:21:31,23.0,Male,NaN,South Africa,NaN,Online only,Often,Local e-commerce,...,Sometimes,$150-300,Digital wallet,"Yes, occasionally",6.0,4.0,1.0,More variety,Try product before buying,Online
356,357,13/08/2026 10:45:43,24.0,Female,NaN,United States,"Under $1,000",Equal mix,Occasionally,Brand websites,...,Sometimes,$50-150,Credit Card,"Yes, occasionally",10.0,5.0,3.0,Better prices,Trust,NaN
369,370,08/07/2026 03:13:09,22.0,Female,NaN,Vietnam,"Under $1,000",Online only,Occasionally,Global marketplace (Amazon etc.),...,Often,$150-300,Debit Card,"No, never",NaN,6.0,2.0,More variety,No delivery wait,Online
386,387,19/08/2026 17:01:42,21.0,Prefer not to say,NaN,Brazil,"Under $1,000",Online only,Occasionally,Brand websites,...,Sometimes,$50-150,Digital wallet,NaN,5.0,7.0,2.0,More variety,Trust,Online
446,447,16/07/2026 14:06:51,17.0,Female,NaN,India,"Under $1,000",In-store only,Rarely,Brand websites,...,Sometimes,Under $50,Credit Card,"No, never",9.0,7.0,2.0,Convenience,Try product before buying,Offline
496,497,28/06/2026 15:20:50,22.0,Prefer not to say,NaN,Colombia,"Under $1,000",Online only,Occasionally,Global marketplace (Amazon etc.),...,Often,Under $50,Digital wallet,"No, never",9.0,5.0,2.0,More variety,Try product before buying,Equal / both

In [72]:
df["Occupation_Status"]=df["Occupation_Status"].fillna("Student")

In [73]:
df["Country_Region"].value_counts()

Country_Region
India             66
United States     56
Brazil            38
Mexico            35
Kenya             26
Indonesia         26
Egypt             25
Philippines       23
Nigeria           23
United Kingdom    23
Pakistan          23
Colombia          21
Vietnam           20
South Africa      20
Turkiye           19
Poland            19
Germany           11
Slovakia           6
Name: count, dtype: int64

In [74]:
df["Country_Region"].unique()

array(['Philippines', 'Brazil', 'India', nan, 'United States', 'Egypt',
       'Indonesia', 'Mexico', 'United Kingdom', 'Nigeria', 'Pakistan',
       'Vietnam', 'Kenya', 'Slovakia', 'Colombia', 'Poland', 'Turkiye',
       'South Africa', 'Germany'], dtype=object)

In [75]:
df[df["Country_Region"].isna() ]

,Response_ID,Timestamp,Age,Gender,Occupation_Status,Country_Region,Monthly_Income_Range,Shop_Most_Where,Online_Shopping_Frequency,Preferred_Platform,...,Return_Frequency,Avg_Monthly_Spend_NonEssentials,Preferred_Payment_Method,Uses_BNPL_Installments,Online_Shopping_Satisfaction_Score,Trust_In_Online_Reviews_Score,Regret_After_Purchase_Frequency,Reason_Prefer_Online,Reason_Prefer_InStore,Best_Shopping_Mode
3,4,23/06/2026 21:24:21,20.0,Male,Student,NaN,"Under $1,000",In-store only,Occasionally,Brand websites,...,Never,Under $50,Debit Card,"No, never",8.0,7.0,3.0,Better prices,Try product before buying,Equal / both
25,26,10/08/2026 12:23:24,16.0,Female,Student,NaN,"$1,000-3,000",In-store only,Often,Physical stores,...,Often,Under $50,Digital wallet,"Yes, occasionally",6.0,7.0,3.0,Better prices,No delivery wait,Equal / both
31,32,06/08/2026 22:51:27,18.0,Male,Student,NaN,"Under $1,000",In-store only,NaN,Physical stores,...,Sometimes,Under $50,Credit Card,"No, never",9.0,5.0,1.0,More variety,Try product before buying,Offline
40,41,22/07/2026 22:54:08,22.0,Male,Student,NaN,"Under $1,000",Equal mix,Always,Local e-commerce,...,Never,$50-150,Debit Card,"No, never",7.0,5.0,4.0,Convenience,Try product before buying,Online
46,47,26/07/2026 05:05:56,19.0,Male,Employed part-time,NaN,"Under $1,000",Equal mix,Often,Brand websites,...,Sometimes,Under $50,NaN,"No, never",7.0,4.0,4.0,Convenience,Try product before buying,Online
106,107,21/06/2026 20:14:53,22.0,Female,Student,NaN,NaN,Online only,Occasionally,Global marketplace (Amazon etc.),...,Never,Under $50,Digital wallet,"Yes, regularly",7.0,7.0,2.0,Convenience,Trust,Online
118,119,24/06/2026 23:56:08,18.0,Male,Student,NaN,"Under $1,000",Equal mix,Occasionally,Brand websites,...,Sometimes,$50-150,Digital wallet,"No, never",7.0,5.0,2.0,Convenience,No delivery wait,Equal / both
124,125,04/08/2026 08:01:27,22.0,Male,Employed part-time,NaN,"$3,000-6,000",Equal mix,Occasionally,Global marketplace (Amazon etc.),...,Sometimes,$300-500,Debit Card,"No, never",7.0,6.0,2.0,Convenience,Not applicable,Offline
133,134,27/06/2026 01:21:58,21.0,Female,Employed full-time,NaN,"$1,000-3,000",Online only,Always,Local e-commerce,...,Often,$50-150,Debit Card,"No, never",8.0,NaN,3.0,Convenience,No delivery wait,Online
169,170,28/06/2026 09:12:03,25.0,Male,Employed full-time,NaN,"$1,000-3,000",Equal mix,Occasionally,Global marketplace (Amazon etc.),...,Sometimes,$150-300,Debit Card,"Yes, occasionally",7.0,5.0,2.0,More variety,Trust,Online
181,182,30/06/2026 07:15:16,28.0,Male,Employed full-time,NaN,"$3,000-6,000",Equal mix,Always,Brand websites,...,Sometimes,$50-150,NaN,"No, never",8.0,10.0,NaN,Convenience,Not applicable,Equal / both
219,220,22/06/2026 15:08:03,31.0,Male,Employed part-time,NaN,"Under $1,000",In-store only,Always,Global marketplace (Amazon etc.),...,Sometimes,Under $50,Cash,"No, never",6.0,NaN,3.0,More variety,NaN,Offline
227,228,10/07/2026 02:55:08,41.0,Male,Employed part-time,NaN,"$3,000-6,000",Equal mix,Occasionally,Local e-commerce,...,NaN,$150-300,Credit Card,"Yes, occasionally",8.0,9.0,3.0,Not applicable,Try product before buying,Offline
301,302,29/07/2026 06:23:48,17.0,Female,Student,NaN,"$1,000-3,000",Equal mix,Occasionally,Local e-commerce,...,Sometimes,$50-150,Cash,"Yes, regularly",8.0,8.0,1.0,More variety,Trust,Equal / both
309,310,23/08/2026 12:44:42,19.0,Female,Student,NaN,"Under $1,000",Equal mix,Often,Local e-commerce,...,Never,$300-500,Credit Card,"No, never",7.0,6.0,3.0,Convenience,Try product before buying,Equal / both
331,332,01/08/2026 11:38:47,24.0,Male,Employed full-time,NaN,"Under $1,000",Online only,Occasionally,Physical stores,...,Never,Under $50,NaN,"No, never",7.0,7.0,1.0,Better prices,Try product before buying,NaN
336,337,26/07/2026 05:17:05,16.0,Male,Student,NaN,"Under $1,000",Online only,Occasionally,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"Yes, regularly",7.0,5.0,3.0,More variety,Trust,Online
367,368,17/07/2026 16:28:07,28.0,Female,Employed part-time,NaN,"$1,000-3,000",Equal mix,Often,Global marketplace (Amazon etc.),...,Often,$150-300,Debit Card,"No, never",8.0,4.0,1.0,Convenience,Not applicable,Offline
408,409,13/08/2026 11:35:38,18.0,Female,Employed part-time,NaN,"Under $1,000",Equal mix,Often,Physical stores,...,Often,$300-500,Debit Card,"No, never",7.0,7.0,2.0,Better prices,Trust,Online
437,438,28/07/2026 10:46:50,33.0,Male,Employed part-time,NaN,"Under $1,000",In-store only,Occasionally,Local e-commerce,...,Often,$50-150,Credit Card,"Yes, occasionally",8.0,6.0,1.0,More variety,No delivery wait,Offline

In [76]:
df[["Country_Region" , "Monthly_Income_Range"]]
df[["Country_Region" , "Occupation_Status" ]]

     Country_Region   Occupation_Status
0       Philippines             Student
1            Brazil  Employed part-time
2             India             Student
3               NaN             Student
4     United States  Employed full-time
..              ...                 ...
495           India  Employed full-time
496        Colombia             Student
497          Brazil             Student
498  United Kingdom  Employed full-time
499         Turkiye             Student

[500 rows x 2 columns]

In [77]:
pd.crosstab(df["Country_Region"], df["Primary_Device"])

Primary_Device  Laptop  Smartphone  Tablet
Country_Region
Brazil              15          21       2
Colombia             7          11       2
Egypt                8          16       1
Germany              1          10       0
India               15          46       4
Indonesia           12          13       0
Kenya                8          17       1
Mexico               9          25       1
Nigeria              3          19       1
Pakistan             8          13       2
Philippines          6          14       2
Poland               5          12       1
Slovakia             1           5       0
South Africa         4          13       1
Turkiye              5          13       1
United Kingdom      12          10       1
United States       20          32       4
Vietnam              7          12       0

In [78]:
pd.crosstab(
    df["Country_Region"],
    df["Primary_Device"],
    normalize="index"
)
pd.crosstab(
    df["Country_Region"].isna(),
    df["Primary_Device"],
    normalize="index"
)

Primary_Device    Laptop  Smartphone    Tablet
Country_Region
False           0.309322    0.639831  0.050847
True            0.350000    0.650000  0.000000

In [79]:
pd.crosstab(
    df["Country_Region"],
    df["Preferred_Payment_Method"],
    normalize="index"
)
pd.crosstab(
    df["Country_Region"].isna(),
    df["Preferred_Payment_Method"],
    normalize="index"
)

Preferred_Payment_Method      Cash  Credit Card  Debit Card  Digital wallet
Country_Region
False                     0.132479     0.224359    0.258547        0.384615
True                      0.117647     0.235294    0.470588        0.176471

In [80]:
pd.crosstab(
    df["Country_Region"],
    df["Monthly_Income_Range"],
    normalize="index"
)
pd.crosstab(
    df["Country_Region"].isna(),
    df["Monthly_Income_Range"],
    normalize="index"
)

Monthly_Income_Range  $1,000-3,000  $3,000-6,000   $6,000+  Under $1,000
Country_Region
False                     0.254348      0.134783  0.076087      0.534783
True                      0.263158      0.157895  0.000000      0.578947

In [81]:
pd.crosstab(
    df["Country_Region"],
    df["Preferred_Platform"],
    normalize="index"
)

Preferred_Platform,Brand websites,Global marketplace (Amazon etc.),Local e-commerce,Physical stores
Country_Region,,,,
Brazil,0.277778,0.222222,0.388889,0.111111
Colombia,0.142857,0.571429,0.190476,0.095238
Egypt,0.280000,0.200000,0.320000,0.200000
Germany,0.272727,0.181818,0.363636,0.181818
India,0.187500,0.296875,0.296875,0.218750
Indonesia,0.320000,0.200000,0.120000,0.360000
Kenya,0.120000,0.240000,0.400000,0.240000
Mexico,0.363636,0.272727,0.242424,0.121212
Nigeria,0.391304,0.173913,0.130435,0.304348
Pakistan,0.181818,0.318182,0.136364,0.363636
Philippines,0.272727,0.318182,0.272727,0.136364
Poland,0.157895,0.421053,0.263158,0.157895
Slovakia,0.166667,0.500000,0.166667,0.166667
South Africa,0.100000,0.400000,0.450000,0.050000
Turkiye,0.166667,0.333333,0.388889,0.111111
United Kingdom,0.304348,0.391304,0.217391,0.086957
United States,0.207547,0.188679,0.358491,0.245283
Vietnam,0.250000,0.350000,0.300000,0.100000

In [82]:
df["Country_Region"]=df["Country_Region"].fillna("Germany")

In [83]:
df[df["Monthly_Income_Range"].isna()]

,Response_ID,Timestamp,Age,Gender,Occupation_Status,Country_Region,Monthly_Income_Range,Shop_Most_Where,Online_Shopping_Frequency,Preferred_Platform,...,Return_Frequency,Avg_Monthly_Spend_NonEssentials,Preferred_Payment_Method,Uses_BNPL_Installments,Online_Shopping_Satisfaction_Score,Trust_In_Online_Reviews_Score,Regret_After_Purchase_Frequency,Reason_Prefer_Online,Reason_Prefer_InStore,Best_Shopping_Mode
70,71,30/07/2026 15:14:33,24.0,Prefer not to say,Self-employed,India,NaN,Equal mix,Rarely,Global marketplace (Amazon etc.),...,Never,$150-300,Digital wallet,"No, never",8.0,5.0,1.0,More variety,Try product before buying,Offline
77,78,22/08/2026 12:45:17,25.0,Male,Student,India,NaN,Online only,Occasionally,Global marketplace (Amazon etc.),...,Sometimes,$50-150,Digital wallet,"Yes, regularly",6.0,7.0,1.0,Not applicable,Try product before buying,Online
90,91,02/08/2026 11:07:43,26.0,Prefer not to say,Self-employed,United States,NaN,Online only,Occasionally,Brand websites,...,Often,Under $50,Debit Card,"No, never",7.0,9.0,3.0,More variety,No delivery wait,Online
106,107,21/06/2026 20:14:53,22.0,Female,Student,Germany,NaN,Online only,Occasionally,Global marketplace (Amazon etc.),...,Never,Under $50,Digital wallet,"Yes, regularly",7.0,7.0,2.0,Convenience,Trust,Online
163,164,31/07/2026 12:03:55,24.0,Female,Student,Philippines,NaN,Online only,Rarely,Brand websites,...,Never,$50-150,NaN,NaN,NaN,8.0,1.0,Convenience,Trust,Online
189,190,02/07/2026 15:35:05,37.0,Male,Employed part-time,Kenya,NaN,Online only,Occasionally,Brand websites,...,Never,Under $50,Debit Card,"Yes, occasionally",7.0,4.0,2.0,NaN,Try product before buying,Online
214,215,05/08/2026 01:31:39,18.0,Male,Unemployed,Kenya,NaN,NaN,Occasionally,Local e-commerce,...,Never,$50-150,Debit Card,"Yes, occasionally",7.0,6.0,4.0,More variety,Trust,Equal / both
220,221,26/06/2026 20:36:09,22.0,Male,Employed part-time,Philippines,NaN,In-store only,Occasionally,Brand websites,...,Sometimes,$50-150,Cash,"Yes, occasionally",9.0,2.0,3.0,Convenience,No delivery wait,Offline
224,225,24/06/2026 04:32:28,21.0,Female,Student,Colombia,NaN,Equal mix,Always,Local e-commerce,...,Never,$50-150,Debit Card,"No, never",NaN,NaN,NaN,NaN,NaN,NaN
229,230,04/08/2026 18:21:02,17.0,Male,Student,Philippines,NaN,Online only,Rarely,Brand websites,...,Never,Under $50,Credit Card,"No, never",8.0,5.0,1.0,More variety,No delivery wait,Online
263,264,13/08/2026 13:23:02,17.0,Female,Student,Indonesia,NaN,In-store only,Often,Physical stores,...,Never,Under $50,Credit Card,"No, never",9.0,9.0,2.0,Convenience,Not applicable,Offline
299,300,26/06/2026 02:47:08,47.0,Male,Employed full-time,South Africa,NaN,NaN,Occasionally,Global marketplace (Amazon etc.),...,Never,$50-150,Cash,"No, never",6.0,7.0,3.0,More variety,No delivery wait,Equal / both
338,339,24/08/2026 03:52:28,33.0,Female,Employed full-time,India,NaN,Equal mix,Often,Physical stores,...,Sometimes,$150-300,Digital wallet,"No, never",7.0,7.0,3.0,Better prices,Try product before buying,Offline
354,355,02/07/2026 21:30:28,18.0,Female,Student,United States,NaN,In-store only,Occasionally,Physical stores,...,Never,Under $50,Debit Card,"No, never",8.0,8.0,1.0,More variety,Try product before buying,Equal / both
355,356,07/07/2026 20:21:31,23.0,Male,Student,South Africa,NaN,Online only,Often,Local e-commerce,...,Sometimes,$150-300,Digital wallet,"Yes, occasionally",6.0,4.0,1.0,More variety,Try product before buying,Online
378,379,04/08/2026 11:17:19,30.0,Male,Employed full-time,United Kingdom,NaN,Equal mix,Occasionally,Brand websites,...,Sometimes,NaN,Digital wallet,"No, never",7.0,9.0,1.0,Better prices,NaN,Online
383,384,26/06/2026 19:38:16,39.0,Male,Employed full-time,Brazil,NaN,Online only,Often,Global marketplace (Amazon etc.),...,Never,$50-150,Digital wallet,"No, never",8.0,10.0,1.0,Not applicable,Trust,Online
422,423,20/07/2026 11:19:40,23.0,Female,Student,Mexico,NaN,Equal mix,Rarely,Physical stores,...,Sometimes,Under $50,Digital wallet,"Yes, occasionally",6.0,6.0,3.0,NaN,Not applicable,Online
476,477,20/06/2026 02:10:10,34.0,Male,Employed part-time,South Africa,NaN,Equal mix,Occasionally,Global marketplace (Amazon etc.),...,Sometimes,Under $50,Digital wallet,"No, never",3.0,8.0,2.0,More variety,Trust,Online
477,478,16/08/2026 15:53:11,18.0,Male,Student,Turkiye,NaN,Online only,NaN,NaN,...,Sometimes,$50-150,Debit Card,"No, never",6.0,5.0,3.0,More variety,Try product before buying,Online
497,498,23/06/2026 05:27:31,26.0,Male,Student,Brazil,NaN,Equal mix,Often,Brand websites,...,Never,$150-300,Digital wallet,"No, never",8.0,5.0,1.0,Better prices,Trust,Offline

In [95]:
df[["Monthly_Income_Range" ,"Avg_Monthly_Spend_NonEssentials"]]

pd.crosstab(df["Monthly_Income_Range"] , df["Avg_Monthly_Spend_NonEssentials"] , normalize="index")
pd.crosstab(df["Monthly_Income_Range"].isna(), df["Avg_Monthly_Spend_NonEssentials"] , normalize="index")

Avg_Monthly_Spend_NonEssentials,$150-300,$300-500,$50-150,$500+,Under $50
Monthly_Income_Range,,,,,
False,0.197917,0.0875,0.3,0.041667,0.372917

In [90]:
# df["Monthly_Income_Range"]=df["Monthly_Income_Range"].fillna("Under $1,000")

In [94]:
pd.crosstab(df["Monthly_Income_Range"], df["Occupation_Status"] , normalize="index")
df[df["Occupation_Status"] == "Student"]["Monthly_Income_Range"].value_counts(normalize=True)

Monthly_Income_Range
Under $1,000    0.722008
$1,000-3,000    0.189189
$3,000-6,000    0.057915
$6,000+         0.030888
Name: proportion, dtype: float64

In [99]:
pd.crosstab(df["Shop_Most_Where"] , df["Preferred_Platform"] , normalize="index")

Preferred_Platform,Brand websites,Global marketplace (Amazon etc.),Local e-commerce,Physical stores
Shop_Most_Where,,,,
Equal mix,0.225410,0.274590,0.307377,0.192623
In-store only,0.202899,0.275362,0.318841,0.202899
Online only,0.261146,0.299363,0.254777,0.184713

In [98]:
df["Shop_Most_Where"].isna().value_counts()

Shop_Most_Where
False    484
True      16
Name: count, dtype: int64

In [100]:
df["Shop_Most_Where"]=df["Shop_Most_Where"].fillna("Equal Mix")

In [101]:
df["Shop_Most_Where"].isna().sum()

np.int64(0)

In [102]:
df["Online_Shopping_Frequency"].value_counts()

Online_Shopping_Frequency
Occasionally    240
Often           132
Rarely           58
Always           51
Name: count, dtype: int64

In [103]:
df[df["Online_Shopping_Frequency"].isna()]

,Response_ID,Timestamp,Age,Gender,Occupation_Status,Country_Region,Monthly_Income_Range,Shop_Most_Where,Online_Shopping_Frequency,Preferred_Platform,...,Return_Frequency,Avg_Monthly_Spend_NonEssentials,Preferred_Payment_Method,Uses_BNPL_Installments,Online_Shopping_Satisfaction_Score,Trust_In_Online_Reviews_Score,Regret_After_Purchase_Frequency,Reason_Prefer_Online,Reason_Prefer_InStore,Best_Shopping_Mode
31,32,06/08/2026 22:51:27,18.0,Male,Student,Germany,"Under $1,000",In-store only,NaN,Physical stores,...,Sometimes,Under $50,Credit Card,"No, never",9.0,5.0,1.0,More variety,Try product before buying,Offline
32,33,26/06/2026 15:42:13,19.0,Prefer not to say,Student,Brazil,"$3,000-6,000",Equal mix,NaN,Global marketplace (Amazon etc.),...,Sometimes,$150-300,Debit Card,"Yes, regularly",6.0,10.0,2.0,More variety,Try product before buying,Equal / both
38,39,13/08/2026 15:42:47,29.0,Female,Unemployed,Nigeria,"Under $1,000",Equal mix,NaN,Physical stores,...,Never,Under $50,Credit Card,"No, never",9.0,6.0,NaN,More variety,No delivery wait,Online
60,61,24/08/2026 20:32:11,21.0,Female,Student,India,"Under $1,000",Online only,NaN,Global marketplace (Amazon etc.),...,Never,Under $50,Digital wallet,"Yes, regularly",9.0,6.0,2.0,Not applicable,Trust,Online
62,63,02/08/2026 08:13:58,20.0,Female,Student,Brazil,"$1,000-3,000",Equal mix,NaN,Brand websites,...,Sometimes,$150-300,Cash,"Yes, regularly",3.0,3.0,1.0,More variety,Try product before buying,Online
80,81,30/06/2026 13:31:27,21.0,Female,Employed full-time,Vietnam,"$6,000+",Online only,NaN,Local e-commerce,...,Never,$500+,Credit Card,"Yes, occasionally",10.0,6.0,1.0,Convenience,Trust,Equal / both
104,105,19/08/2026 13:56:09,48.0,Male,Employed full-time,Indonesia,"$3,000-6,000",Equal mix,NaN,Brand websites,...,Sometimes,Under $50,Credit Card,"No, never",7.0,6.0,1.0,More variety,Not applicable,Offline
109,110,09/08/2026 02:39:02,22.0,Female,Student,Turkiye,"Under $1,000",Online only,NaN,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"Yes, occasionally",9.0,7.0,2.0,Not applicable,No delivery wait,Online
148,149,19/08/2026 09:28:17,21.0,Female,Student,Indonesia,"Under $1,000",Equal mix,NaN,Brand websites,...,Never,Under $50,Debit Card,"No, never",NaN,NaN,NaN,NaN,NaN,NaN
166,167,08/07/2026 13:13:35,19.0,Male,Student,India,"$1,000-3,000",Online only,NaN,Local e-commerce,...,Never,$300-500,Credit Card,"No, never",8.0,7.0,4.0,NaN,Try product before buying,Online
193,194,01/08/2026 11:22:56,20.0,Male,Student,Poland,"Under $1,000",Equal mix,NaN,Global marketplace (Amazon etc.),...,Never,Under $50,Credit Card,"Yes, occasionally",6.0,9.0,3.0,More variety,No delivery wait,Equal / both
314,315,10/08/2026 21:40:11,22.0,Male,Self-employed,United States,"$6,000+",Equal mix,NaN,Physical stores,...,Never,$50-150,Digital wallet,"Yes, occasionally",8.0,3.0,2.0,More variety,No delivery wait,Equal / both
374,375,12/07/2026 22:56:26,18.0,Female,Employed part-time,Indonesia,"$1,000-3,000",Online only,NaN,Global marketplace (Amazon etc.),...,Never,Under $50,Digital wallet,"Yes, occasionally",8.0,3.0,1.0,More variety,Trust,NaN
417,418,23/06/2026 22:33:29,22.0,Female,Student,United Kingdom,"Under $1,000",Equal mix,NaN,Global marketplace (Amazon etc.),...,Never,Under $50,Debit Card,"No, never",5.0,8.0,2.0,Better prices,NaN,NaN
458,459,29/07/2026 21:23:06,34.0,Female,Employed part-time,Germany,"Under $1,000",Equal mix,NaN,Local e-commerce,...,Often,Under $50,Credit Card,"Yes, occasionally",7.0,7.0,4.0,More variety,Trust,Equal / both
460,461,15/07/2026 23:23:02,22.0,Female,Student,Pakistan,"Under $1,000",Online only,NaN,NaN,...,Often,$50-150,Credit Card,"No, never",8.0,5.0,NaN,More variety,Trust,Equal / both
477,478,16/08/2026 15:53:11,18.0,Male,Student,Turkiye,"Under $1,000",Online only,NaN,NaN,...,Sometimes,$50-150,Debit Card,"No, never",6.0,5.0,3.0,More variety,Try product before buying,Online
484,485,20/07/2026 09:36:39,31.0,Male,Self-employed,Indonesia,"Under $1,000",Online only,NaN,Physical stores,...,Never,Under $50,Cash,"No, never",8.0,7.0,1.0,More variety,No delivery wait,Online
499,500,14/07/2026 11:16:14,22.0,Female,Student,Turkiye,"$3,000-6,000",Equal mix,NaN,Brand websites,...,Never,$500+,Digital wallet,"Yes, occasionally",7.0,10.0,1.0,Convenience,No delivery wait,Offline

In [104]:
pd.crosstab(df["Online_Shopping_Frequency"] , df["Online_Shopping_Satisfaction_Score"])

Online_Shopping_Satisfaction_Score,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0
Online_Shopping_Frequency,,,,,,,,,
Always,0,0,3,4,9,14,8,4,2
Occasionally,1,5,9,18,42,55,48,25,19
Often,1,0,4,13,19,33,27,16,9
Rarely,0,0,2,5,8,14,15,6,1

In [105]:
df["Online_Shopping_Frequency"]=df["Online_Shopping_Frequency"].fillna("Occasionally")

In [107]:
df["Preferred_Platform"].value_counts()

Preferred_Platform
Global marketplace (Amazon etc.)    141
Local e-commerce                    140
Brand websites                      113
Physical stores                      92
Name: count, dtype: int64

In [108]:
pd.crosstab(df["Preferred_Platform"] , df["Shop_Most_Where"] , normalize="index")

Shop_Most_Where,Equal Mix,Equal mix,In-store only,Online only
Preferred_Platform,,,,
Brand websites,0.026549,0.486726,0.123894,0.362832
Global marketplace (Amazon etc.),0.056738,0.475177,0.134752,0.333333
Local e-commerce,0.021429,0.535714,0.157143,0.285714
Physical stores,0.021739,0.510870,0.152174,0.315217

In [116]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Response_ID                         500 non-null    int64
 1   Timestamp                           500 non-null    object
 2   Age                                 500 non-null    float64
 3   Gender                              500 non-null    object
 4   Occupation_Status                   500 non-null    object
 5   Country_Region                      500 non-null    object
 6   Monthly_Income_Range                500 non-null    object
 7   Shop_Most_Where                     500 non-null    object
 8   Online_Shopping_Frequency           500 non-null    object
 9   Preferred_Platform                  486 non-null    object
 10  Primary_Device                      492 non-null    object
 11  Top_Spending_Category               476 non-null    object
 12  Review_Influence_Score              485 non-null    float64
 13  Social_Ads_Influence_Score          479 non-null    float64
 14  Price_Comparison_Frequency          474 non-null    float64
 15  Discount_Importance_Score           477 non-null    float64
 16  Follows_Brands_On_Social            489 non-null    object
 17  Likely_To_Buy_After_Ad_Score        475 non-null    float64
 18  Makes_Shopping_List                 476 non-null    object
 19  Impulse_Purchase_Frequency          484 non-null    float64
 20  Return_Frequency                    483 non-null    object
 21  Avg_Monthly_Spend_NonEssentials     480 non-null    object
 22  Preferred_Payment_Method            485 non-null    object
 23  Uses_BNPL_Installments              488 non-null    object
 24  Online_Shopping_Satisfaction_Score  457 non-null    float64
 25  Trust_In_Online_Reviews_Score       450 non-null    float64
 26  Regret_After_Purchase_Frequency     448 non-null    float64
 27  Reason_Prefer_Online                446 non-null    object
 28  Reason_Prefer_InStore               455 non-null    object
 29  Best_Shopping_Mode                  449 non-null    object
dtypes: float64(10), int64(1), object(19)
memory usage: 117.3+ KB

In [121]:
cat_cols = df.select_dtypes(include=["object", "category"]).columns
df[cat_cols] = df[cat_cols].fillna("unknown")

In [118]:
# Select numeric columns and fill their nulls with their respective medians
df[df.select_dtypes(include=["number"]).columns] = df.select_dtypes(include=["number"]).fillna(df.median(numeric_only=True))

In [122]:
df.isna().sum()

Response_ID                           0
Timestamp                             0
Age                                   0
Gender                                0
Occupation_Status                     0
Country_Region                        0
Monthly_Income_Range                  0
Shop_Most_Where                       0
Online_Shopping_Frequency             0
Preferred_Platform                    0
Primary_Device                        0
Top_Spending_Category                 0
Review_Influence_Score                0
Social_Ads_Influence_Score            0
Price_Comparison_Frequency            0
Discount_Importance_Score             0
Follows_Brands_On_Social              0
Likely_To_Buy_After_Ad_Score          0
Makes_Shopping_List                   0
Impulse_Purchase_Frequency            0
Return_Frequency                      0
Avg_Monthly_Spend_NonEssentials       0
Preferred_Payment_Method              0
Uses_BNPL_Installments                0
Online_Shopping_Satisfaction_Score    0
Trust_In_Online_Reviews_Score         0
Regret_After_Purchase_Frequency       0
Reason_Prefer_Online                  0
Reason_Prefer_InStore                 0
Best_Shopping_Mode                    0
dtype: int64